channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - matplotlib-base
  - cartopy=0.16.0
  - pip:
    - earthengine-api==0.1.145
    - google-api-core==1.3.0
    - google-api-python-client==1.7.3
    - google-auth==1.5.0
    - google-auth-httplib2==0.0.3
    - oauth2client==4.1.2
